# Generated by Django 6.1 on 2026-08-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_address_userprofile_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("Genre", "G"), ("Homme", "H"), ("Femme", "F")],
                default="Genre",
                max_length=5,
            ),
        ),
    ]
