# Generated by Django 6.1 on 2026-08-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("---", "---"), ("Homme", "Homme"), ("Femme", "Femme")],
                max_length=5,
            ),
        ),
    ]
