# Generated by Django 6.1 on 2026-08-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_userprofile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
