# Generated by Django 6.1 on 2026-09-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5)),
                ('date_heure', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('---', '---'), ('Brouillage', 'Brouillage'), ('Controle de conformite', 'Controle de conformite'), ('Controle Points Hauts', 'Controle Points Hauts'), ('Mesure EMF', 'Mesure EMF')], default='---', max_length=25)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('etat', models.CharField(choices=[('---', '---'), ('En attente', 'En attente'), ('En cours', 'En cours'), ('Teminee', 'Terminee')], default='---', max_length=25)),
                ('responsable', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
